# Generated by Django 3.1.7 on 2021-04-01 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvUploadFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.FileField(
                        upload_to="csv_files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv"],
                                message=["拡張子が「csv」のファイルを選択してください。"],
                            )
                        ],
                    ),
                ),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CSV file",
                "verbose_name_plural": "CSV files",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(
                                999999999999
                            ),
                        ],
                    ),
                ),
                (
                    "fruit_price_when_sold",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "proceeds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "sold_on",
                    models.DateTimeField(
                        validators=[sales.models.reject_future_date_time]
                    ),
                ),
                (
                    "fruit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="stock.fruit",
                    ),
                ),
            ],
            options={
                "verbose_name": "sale",
                "verbose_name_plural": "sales",
            },
        ),
    ]
